server:
  port: 10000

logging:
  level:
    root: WARN
    es.upm.api: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  hosting: AWS

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iwvgdevopsdb
    username: postgres
    password: postgres

