server:
  port: 8080

app:
  hosting: render

spring:
  jpa:
    hibernate:
      ddl-auto: update
  #Valores creados en Render -> Databases -> Database -> Connect
  datasource:
    dbcp2:
      driver-class-name: org.posgresql.Driver
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE-PASSWORD}