name: CD
on:
  push:
    branches: ['master']

env:
  REPOSITORY: ${{ github.repository }} # <user>/<repo>
  GHCR_URL: ghcr.io # GitHub Container Registry

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on Render Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🏷️ Extract artifact from pom
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      # 1º Crear Token de Acceso Personal:
      #    GitHub → Settings → Developer settings → Personal access tokens → Generate new token (classic)
      #    Permisos mínimos: write:packages, read:packages, delete:packages, repo
      #
      # 2º Crear secret en GitHub:
      #    Repo → Settings → Secrets and variables → Actions → New repository secret
      #    Name: GHCR_PERSONAL_ACCESS_TOKEN, Value: <tu token>
      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: 🐳 Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:latest

      - name: 🚀 Deploy on AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_MAIN }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_MAIN }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_MAIN }}
          script: |
            sudo docker rm -f postgres || true
            sudo docker network create devops || true
            sudo docker run -d \
              --name postgres \
              --restart always \
              --network devops \
              -p 8080:8080 \
              -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
              -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
              -e POSTGRES_DB=iwvgdevopsdb \
              postgres:15.10

            echo "✅ Deploy exitoso"
            docker image prune --filter "until=12h" -f